---
name: Run Update

on:
  push:
    branches:
    - 'renovate/*'
    paths:
    - '**/update.sh'

jobs:
  format-code:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # give GITHUB_TOKEN permission to commit changes

    steps:
    - uses: actions/checkout@v3
    - name: Run maintenance
      run: |
        ./app1/update.sh
    - uses: pre-commit/action@v3.0.0
      with:
        extra_args: --all-files --verbose
    # Commit all changed files back to the repository
    - uses: stefanzweifel/git-auto-commit-action@v4
      if: always()  # run even if pre-commit hook made fixes
      with:
        commit_author: "renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>"
        commit_message: "chore(deps): Running upgrade scripts"
