---
name: Run Update

on:
  push:
    branches:
    - 'renovate/*'

jobs:
  format-code:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
    - uses: actions/checkout@v3
    - name: Run maintenance
      run: |
        ./app1/update.sh
    - uses: pre-commit/action@v3.0.0
      with:
        extra_args: --all-files --verbose
    # Commit all changed files back to the repository
    - uses: stefanzweifel/git-auto-commit-action@v4
      if: always()  # run even if pre-commit hook made fixes
      with:
        commit_author: "renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>"
        commit_message: "chore(deps): Running upgrade scripts"
