---
name: Update Scripts

on:
  push:
    branches:
    - 'renovate/*'
    paths:
    - '**/update.sh'

jobs:
  update-steps:
    runs-on: ubuntu-22.04

    permissions:
      contents: write  # give GITHUB_TOKEN permission to commit changes

    steps:
    - uses: asdf-vm/actions/setup@v2
    - name: Install Helm
      run: |
        asdf plugin add helm
        asdf install helm
    - uses: actions/checkout@v3
    - id: files
      name: Get changed maintenance files
      uses: Ana06/get-changed-files@v2.2.0
    - name: Run maintenance scripts
      run: |
        changed_files="${{ steps.files.outputs.all }}"
        echo $changed_files | xargs -n1 echo | while IFS=' ' read -r changed_file; do
          if [[ "${changed_file}" == *"update.sh"* ]]; then
            echo "Running update script ${changed_file}"
            bash "${changed_file}"
          fi
        done
    - uses: pre-commit/action@v3.0.0
      continue-on-error: true
      with:
        extra_args: --all-files --verbose
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:  # overwrite commit author so Renovate does not stop keeping the branch up-to-date
        commit_author: "renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>"
        commit_message: "chore(deps): Running upgrade scripts"
