---
name: Update Scripts

on:
  push:
    branches:
    - 'renovate/*'
    paths:
    - '**/update.sh'

jobs:
  update-steps:
    runs-on: ubuntu-22.04

    permissions:
      contents: write  # give GITHUB_TOKEN permission to commit changes

    steps:
    - uses: actions/checkout@v3
    - uses: asdf-vm/actions/setup@v2
    - id: files
      name: Get changed files
      uses: tj-actions/changed-files@v35
    - name: Run maintenance scripts
      run: |
        changed_files="${{ steps.files.outputs.modified_files }}"
        echo $changed_files | xargs -n1 echo | while IFS=' ' read -r changed_file; do
          if [[ "${changed_file}" == *"update.sh"* ]]; then
            tools="$(< "${changed_file}" grep "# asdf-tools-used=" | cut -d= -f2)"
            echo "Discovered asdf tools for ${changed_file}: ${tools}"
            echo "$tools" | xargs -n1 echo | while IFS=' ' read -r tool; do
              if [[ -n "${tool//[[:blank:]]/}" ]]; then
                echo "Installing asdf tool ${tool}"
                asdf plugin add "${tool}"
                asdf install "${tool}"
              fi
            done
            echo "Running update script ${changed_file}"
            bash "${changed_file}"
          fi
        done
    - uses: pre-commit/action@v3.0.1
      continue-on-error: true  # in case the pre-commit hooks change formatting, exit code is 1 (expected)
      with:
        extra_args: trailing-whitespace --all-files --verbose
    - uses: pre-commit/action@v3.0.1
      continue-on-error: true  # in case the pre-commit hooks change formatting, exit code is 1 (expected)
      with:
        extra_args: end-of-file-fixer --all-files --verbose
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:  # overwrite commit author so Renovate does not stop keeping the branch up-to-date
        commit_author: "renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>"
        commit_message: "chore(deps): Running upgrade scripts"
